services:
  rstudio:
    build:
      context: .
      dockerfile: rstudio.Dockerfile
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: true
    volumes:
      - ./scripts:/home/rstudio/workspaces
